export { PROFILE_SLICE_NAME } from './model/types/profile';
export type { ProfileSchema, Profile } from './model/types/profile';
export { profileReducer } from './model/slice/profileSlice';
import { profileSliceActions } from './model/slice/profileSlice';
import { fetchProfileData } from './model/services/fetchProfileData/fetchProfileData';
import { updateProfileData } from './model/services/updateProfileData/updateProfileData';
export { ProfileCard } from './ui/ProfileCard/ProfileCard';
export { getProfile } from './model/selectors/getProfile/getProfile';
export { getProfileForm } from './model/selectors/getProfileForm/getProfileForm';
export { getProfileError } from './model/selectors/getProfileError/getProfileError';
export { getProfileIsLoading } from './model/selectors/getProfileIsLoading/getProfileIsLoading';
export { getProfileReadOnly } from './model/selectors/getProfileReadonly/getProfileReadOnly';
export { getProfileValidateErrors } from './model/selectors/getProfileValidateErrors/getProfileValidateErrors';
export const profileActions = { ...profileSliceActions, fetchProfileData, updateProfileData };
