name: linting, testing, building
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v2
      - name: Starting Node.js ${{matrix.node-version}}
        uses: actions/setup-node@v1
        with:
          node-version: ${{matrix.node-version}}
      - name: install modules
        run: npm i --legacy-peer-deps
      - name: build project
        run: npm run build
      - name: lint typescript
        run: npm run check
      - name: lint scss
        run: npm run check:style
      - name: unit testing
        run: npm run test:unit
      - name: build storybook
        run: npm run storybook:build
      - name: screenshot tests
        run: npm run test:ui:ci
